### ISSUE TITLE
path-parms thats not a function-param?

### ISSUE THREAD

**Issue by puggan** [uderline/openapi-php-attributes#10]
I have a parameter in my path, but it's not sent as a parameter to the function.
How can i make it generate a valid openapi.json? (without adding an unsued function-parameter)

* Could you automaticly search for `{}` in the path, and see if one is missing?
* Could we have another Attribute, like: PathParameter

```php
    #[
        GET('/api/{version}/web/{market}/airport-list', [], 'List all Airports'),
        PathParameter(name: 'version'),
        PathParameter(name: 'market'),
        Response(schemaType: SchemaType::ARRAY, ref: Airports::class)
    ]
    public function listAirports(): JsonResponse
```

**Comment by puggan** [comment]
PR #12

**Comment by puggan** [comment]
PR #14 PathParameter

Pros:
 * You can fully define your path parameters, even when the method dosn't have a paramter with that name.
 * Works togehter with PR #12

**Comment by uderline** [comment]
Hi !

This totally makes sense. Let me check the PRs this week-end

Thanks for your contributions ;)
