### ISSUE TITLE
Undefined array key "security"

### ISSUE THREAD

**Issue by puggan** [uderline/openapi-php-attributes#21]
Looks like a SecurityScheme is required in the current version, 
If you want to enforce using a SecurityScheme, throw your own exception, 
or allow apis that have zero SecurityScheme.

```
PHP Warning:  Undefined array key "security" in <project>/vendor/uderline/openapi-php-attributes/src/Generator.php on line 91
PHP Stack trace:
PHP   1. {main}() <project>/vendor/uderline/openapi-php-attributes/opag:0
PHP   2. OpenApiGenerator\Generator->generate() <project>/vendor/uderline/openapi-php-attributes/opag:38
PHP   3. OpenApiGenerator\Generator->makeFinalArray() <project>/vendor/uderline/openapi-php-attributes/src/Generator.php:77
```

**Comment by uderline** [comment]
Hi ! 

Yes, there's a big problem without errors not being caught and that's my next goal.
Thanks for your contribution - I'll check this (and your other PRs) out this week-end
