### ISSUE TITLE
invalid securityScheme

### ISSUE THREAD

**Issue by puggan** [uderline/openapi-php-attributes#25]
![image](https://user-images.githubusercontent.com/866668/185421453-cf13eeeb-d4f4-4477-afb0-37ab897edcf1.png)

app.swaggerhub.com gives the warning:
`should NOT have additional properties additionalProperty: bearerFormat, scheme`

Maybe an array_filter() around:
https://github.com/uderline/openapi-php-attributes/blob/6e5be682c84ac5e6c8f2da47918729150909ee8f/src/Attributes/SecurityScheme.php#L29-L37

**Comment by uderline** [comment]
If the recommendation is to not have it. Maybe the fields should be removed. What do you think ?

**Comment by uderline** [comment]
1.6.4 should fix the issue

The security key has been removed that is replaced by a slug of the name (or the type if "name" is not provided).

An additional attribute has been added
```php
#[
  SecurityScheme(type: 'http', ...)
  Security(['http']
)
```
